/* eslint-disable prettier/prettier */
export const drogasil = 'https://static.ifood-static.com.br/image/upload/t_medium/logosgde/f68fe11b-507a-4e25-8657-0e9bb21b5f99/202304241356_wP4d_i.jpg?imwidth=128'
export const saude50 = 'https://static.ifood-static.com.br/image/upload/t_high/discoveries/1904FarmaSaudeeAutocuidadoate50OFFprincipal1_R7IU.png?imwidth=3840'
export const farma30 = 'https://static.ifood-static.com.br/image/upload/t_high/discoveries/0305farmacinha30principal_YWVE.png?imwidth=3840'
export const tylenol = 'https://static.ifood-static.com.br/image/upload/t_high/discoveries/1205tylenol15principal_2iZc.png?imwidth=3840'
export const aptamil = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/MediumBanners9_dxZu.png?imwidth=256'
export const novalgina = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/MediumBanners3_qIwO.png?imwidth=256'
export const ozempic = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/MediumBanners2_NUsE.png?imwidth=256'
export const buscopan = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/MediumBanners4_vvEO.png?imwidth=256'
export const nan = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/MediumBanners1_Ij7e.png?imwidth=256'
export const paguemenos = 'https://static.ifood-static.com.br/image/upload/t_medium/logosgde/df7b7993-bce6-4824-9705-c168a67976d7/202303221957_1E94.png?imwidth=128'

export const promo = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Promocoes_vBG9.png?imwidth=128'
export const presentes = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Designsemnome34_lTR5.png?imwidth=128'
export const bebe = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Bebes_QNRO.png?imwidth=128'
export const remedio = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Remedios_eULp.png?imwidth=128'
export const gripe = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Gripes_O3bH.png?imwidth=128'
export const testes = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Testes_EOBf.png?imwidth=128'
export const vitaminas = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Vitaminicos_L7SZ.png?imwidth=128'
export const higiene = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Higiene_hbHW.png?imwidth=128'
