/* eslint-disable prettier/prettier */
export const lanches = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/lanches_HC15.png?imwidth=128'
export const pizza = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/pizzas_KxCO.png?imwidth=128'
export const japonesa = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/japonesa_FP14.png?imwidth=128'
export const brasileira = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/brasileira_1XfT.png?imwidth=128'
export const acai = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/acai_WTXp.png?imwidth=128'
export const arabe = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/arabe_8LSW.png?imwidth=128'
export const saudavel = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/saudaveis_aTKz.png?imwidth=128'
export const italiana = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/italiana_Y4je.png?imwidth=128'
export const doces = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/docesebolos_RfHb.png?imwidth=128'
export const pastel = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/pastel2_qeWo.png?imwidth=128'
export const chinesa = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/chinesa_pIpW.png?imwidth=128'
export const carnes = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/carnes_T64X.png?imwidth=128'
export const salgados = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/salgados_dTNG.png?imwidth=128'
export const sorvetes = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/sorvetes_BD8y.png?imwidth=128'
export const padarias = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/padaria_cF7D.png?imwidth=128'
export const marmitas = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/Marmita2_LXbQ.png?imwidth=128'
export const vegetariana = 'https://static.ifood-static.com.br/image/upload/t_medium/discoveries/vegetariana_XGvO.png?imwidth=128'
